### ISSUE TITLE
Update import statements

### ISSUE THREAD

**Issue by ForestEckhardt** [paketo-buildpacks/go-compiler#4]
Make sure all import statements are updated to point at the paketo-buildpacks org!

**Comment by ForestEckhardt** [comment]
This was done by the following commit:
https://github.com/paketo-buildpacks/go-compiler/commit/325267bce0aeb20038faaf3df89479e46bc6fc80

**Comment by ryanmoran** [comment]
@ForestEckhardt does the above comment mean this can be closed?
